version: '3'
services:
  api-pedramoura:
    image: node:16
    container_name: api-pedramoura
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm install", "npm run start:dev"] 
    ports:
      - "3000:3000"